zeropsio/zcli

src/dns/handler_detectDns.go
src/dns/handler_detectDns_test.go
src/dns/handler_setDns.go

Command system-resolve [was removed](https://askubuntu.com/questions/1409726/systemd-resolve-command-not-found-in-ubuntu-22-04-desktop) in Ubuntu 22.04. Fixing it to work without it.

z1591 - change dns setting for systemd-resolve to resolvectl

---

CHANGELOG.md
go.mod
go.sum
src/cliAction/bucket/s3/handler.go
src/cliAction/bucket/s3/handler_create.go
src/cliAction/bucket/s3/handler_delete.go
src/cliAction/bucket/zerops/handler.go
src/cliAction/bucket/zerops/handler_create.go
src/cliAction/bucket/zerops/handler_delete.go
src/cmd/bucket.go
src/cmd/bucketS3.go
src/cmd/bucketS3Create.go
src/cmd/bucketS3Delete.go
src/cmd/bucketZerops.go
src/cmd/bucketZeropsCreate.go
src/cmd/bucketZeropsDelete.go
src/cmd/deploy.go
src/cmd/di.go
src/cmd/root.go
src/i18n/en.go
src/region/region.go
src/utils/projectService/getProjectById.go
src/utils/projectService/getProjectId.go

- New set of S3 management `bucket` commands with ability to `create` and `delete` buckets
- via `Zerops API`:
- `zcli bucket zerops create projectNameOrId serviceName bucketName [flags]`
- `zcli bucket zerops delete projectNameOrId serviceName bucketName [flags]`
- via `S3 API`.
- `zcli bucket s3 create serviceName bucketName [flags]`
- `zcli bucket s3 delete serviceName bucketName [flags]`

z1951 - Basic S3 bucket management

---

CHANGELOG.md
src/cliAction/buildDeploy/handler_deploy.go
src/utils/archiveClient/handler_findFilesByRules.go
src/utils/archiveClient/handler_findGitFiles.go
src/utils/archiveClient/handler_utils.go

Fixed an issue where `zcli deploy` would not work on Windows when certain formats of paths were passed as parameters.

z2158 - fix deploy on Windows

---

CHANGELOG.md
src/cmd/bucketS3.go
src/cmd/bucketS3Create.go
src/cmd/bucketS3Delete.go
src/cmd/login.go
src/cmd/regionList.go
src/i18n/en.go
src/region/region.go

- `--region` flag with `ZCLI_REGION` env option to the `zcli bucket s3` `create` and `delete` commands

z2226 - bucket s3 commands added option to specify region

---

.github/workflows/tag.yml
.gitignore
CHANGELOG.md
src/utils/archiveClient/handler_findGitFiles.go
src/utils/params/handler.go

- `service log` and `vpn start` were ignoring env and config values for `limit` and `mtu` parameters respectively
- released binaries do not include debug tables and should be about 25% to 30% smaller
- `push` command now correctly pushes all files if called from a repository utilizing git submodules

z2941 - fix uint params ignoring env and config values

---

src/archiveClient/handler_findFilesByRules_test.go
src/archiveClient/handler_findGitFiles.go
src/archiveClient/handler_findGitFiles_test.go
src/archiveClient/handler_utils.go

fixes output of git ls-files command quoting "unusual" ('bytes higher than 0x80' - git config 'core.quotePath' manpage) characters

fix: git ls-files command output quoting on 'unusual' characters

---

CHANGELOG.md
src/archiveClient/handler_findFilesByRules_test.go
src/archiveClient/handler_findGitFiles_test.go

- `go get` would fail due to the `non–ascii.txt` file in one of the test cases. File is now created ad-hoc during the test and then cleaned up.

Remove non ascii file from repo, to fix broken go get

---

CHANGELOG.md
LICENSE
README.md
install.ps1
install.sh
src/cmdBuilder/executeRootCmd.go
src/i18n/en.go
src/i18n/i18n.go
src/wg/linux.go

`resolvectl` is not installed on debian anymore by default: https://www.debian.org/releases/bookworm/amd64/release-notes/ch-information.en.html#systemd-resolved

Added install scripts and missing check for resolvectl

---

README.md

Following URLs are 302 redirects to the original links.
They are just shorter and make it easier for users to check they are indeed from official `zerops.io` domain.

Used shortened links for install scripts (redirect to files on github)

---

src/cmd/scope/scopeProject.go
src/cmd/scope/scopeService.go
src/cmdBuilder/buildCobraCmd.go
src/cmdBuilder/cmd.go
src/cmdBuilder/createRunFunc.go

Removes the need to provide the `--projectId` flag for service scope commands when the `--serviceId` flag is provided.

improvement: don't ask for projectId when serviceId is provided

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/main.yml
.github/workflows/tag.yml
.golangci.yaml
README.md
go.mod
src/cmd/serviceLog.go
src/logger/hooks.go
src/serviceLogs/handler.go
src/serviceLogs/handler_checkInputValues.go
src/storage/handler.go
tools/install.sh

update to go1.23, update workflow go-setup actions, pull request template and add optional dependency for ping command

chore: update to go1.23, github workflows & README.md

---

.github/workflows/main.yml
.github/workflows/tag.yml
CHANGELOG.md

fix: github workflows set CGO_ENABLED=0 on for build job

---

src/cmd/projectImport.go
src/cmd/projectServiceImport.go
src/i18n/en.go
src/yamlReader/readYaml.go

Allow reading yaml content from stdin in import commands. Also fix flag `workingDie` -> `workingDir`.

feat(import): allow to take yaml content from stdin in import commands

---

src/cmd/servicePush.go

The current usage for ``zcli push --serviceId`` is ``zcli push --serviceId z3eHIXPjT0iKAIZATAqg4g`` 
which pushes the code to the service which then gets built and deployed
was required to implement ``zcli push z3eHIXPjT0iKAIZATAqg4g`` without a flag 
made both cases work 
1) ``zcli push --serviceId z3eHIXPjT0iKAIZATAqg4g``
2) ``zcli push z3eHIXPjT0iKAIZATAqg4g``
used references and implementation from ``zcli vpn up`` in ``vpnUp.go``

fix (``servicePush.go``): push without a flag provided

---

src/cmdBuilder/executeRootCmd.go

Table output in non-terminal usages is truncated due to "pretty" table width shrinkage. Leave width infinite if it can't be detected.

fix: truncated information on non-terminal table views

---

CHANGELOG.md
src/cmd/scope/scopeProject.go
src/cmd/scope/scopeService.go
src/entity/repository/service.go
src/entity/service.go

Fixed issue with scoping where Project would not be loaded when `serviceId` flag was used.

Fixed service/project scoping issues

---

CHANGELOG.md
src/serviceLogs/handler_formatByRfc.go

Fixed panic in logs with timestamp without milliseconds

Fixed panic in logs with timestamp without milliseconds

---

.golangci.yaml
Makefile
go.mod
tools/install.sh

chore: bump go version to 1.24 & update golangci-lint
- Closes #

chore: bump go version to 1.24 & update golangci-lint

---

CHANGELOG.md
go.sum
src/archiveClient/handler.go
src/archiveClient/handler_archiveGitFiles.go
src/archiveClient/handler_gitArchiver.go
src/cmd/serviceDeploy.go
src/cmd/servicePush.go
src/i18n/en.go
src/i18n/i18n.go
src/logger/handler.go
src/logger/interface.go
src/uxBlock/blocks.go
src/uxBlock/logs.go
src/uxBlock/mocks/blocks.go

- `--verbose` (shorthand `-v`) flag to `deploy` and `push` commands to log additional data do zcli debug log file

Added verbose flag to push command

---

CHANGELOG.md
src/archiveClient/handler_gitArchiver.go

- `--workspaceState` flag should now work correctly if set to `all`, but the repository has no changes

Fix push command with workspace state set to all

---

src/cmd/project.go
src/cmd/projectEnv.go
src/cmdBuilder/cmd.go

Add new command `project env` which fetches project env file from backend
- Closes #

feat: project env command

---

README.md
install.ps1
src/cmdBuilder/createRunFunc.go
src/constants/zerops.go
src/i18n/en.go

Allow authentication via present ZEROPS_TOKEN environment variable. Stored authentication data created by the `zcli login` takes precedence, if both authentication method are configured.
Only default region is supported with ZEROPS_TOKEN autentication, for now.

feat: authenticate via present ZEROPS_TOKEN environment variable

---

src/cmdBuilder/createRunFunc.go
src/i18n/en.go

login data
ZEROPS_TOKEN environment variable should take precedence over stored zcli login data.

fix: ZEROPS_TOKEN environment variable takes precedence over stored zcli

---

src/cliStorage/handler.go
src/cmd/vpn.go
src/cmd/vpnClear.go
src/cmd/vpnKey.go
src/cmd/vpnKeyList.go.go
src/cmd/vpnKeyRemove.go.go
src/cmd/vpnUp.go
src/cmdBuilder/createRunFunc.go
src/uxBlock/logs.go

Add basic VPN keys management capabilities.

feat: add 'vpn clear' and 'vpn key' commands
